# Generated by Django 4.2.8 on 2026-01-07 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel (DE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Kurzbeschreibung (DE)')),
                ('short_description_en', models.CharField(blank=True, max_length=300, verbose_name='Short Description (EN)')),
                ('description', models.TextField(verbose_name='Beschreibung (DE)')),
                ('description_en', models.TextField(verbose_name='Description (EN)')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='transfers/', verbose_name='Hauptbild')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Grundpreis (EUR)')),
                ('price_per_person', models.BooleanField(default=False, verbose_name='Preis pro Person')),
                ('price_per_km', models.BooleanField(default=False, verbose_name='Preis pro Kilometer')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rabattpreis')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Dauer (Minuten)')),
                ('availability', models.CharField(choices=[('24/7', '24/7 Verfügbar'), ('Täglich', 'Täglich'), ('Wochentags', 'Wochentags'), ('Nach Vereinbarung', 'Nach Vereinbarung')], default='24/7', max_length=50, verbose_name='Verfügbarkeit')),
                ('languages', models.CharField(default='DE, EN', help_text="Komma-getrennte Liste (z.B. 'DE, EN, AR')", max_length=200, verbose_name='Verfügbare Sprachen')),
                ('free_cancellation', models.BooleanField(default=True, verbose_name='Kostenlose Stornierung')),
                ('free_waiting_time', models.PositiveIntegerField(default=60, verbose_name='Kostenlose Wartezeit (Minuten)')),
                ('flight_monitoring', models.BooleanField(default=False, verbose_name='Flugüberwachung')),
                ('meet_greet', models.BooleanField(default=True, verbose_name='Meet & Greet Service')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Empfohlen')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Beliebt')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='tours.location', verbose_name='Von')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='tours.location', verbose_name='Nach')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['-is_featured', '-is_popular', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TransferType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name (DE)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (EN)')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung (DE)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon (e.g., ✈️, 🚗, 🏨)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Transfer-Typ',
                'verbose_name_plural': 'Transfer-Typen',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name (DE)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (EN)')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('capacity', models.PositiveIntegerField(verbose_name='Kapazität (Personen)')),
                ('luggage_capacity', models.PositiveIntegerField(default=2, verbose_name='Koffer-Kapazität')),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Fahrzeugtyp',
                'verbose_name_plural': 'Fahrzeugtypen',
                'ordering': ['order', 'capacity'],
            },
        ),
        migrations.CreateModel(
            name='TransferInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel (DE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='transfers.transfer')),
            ],
            options={
                'verbose_name': 'Inklusion',
                'verbose_name_plural': 'Inklusionen',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TransferImportantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=300, verbose_name='Information (DE)')),
                ('info_en', models.CharField(max_length=300, verbose_name='Information (EN)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_info', to='transfers.transfer')),
            ],
            options={
                'verbose_name': 'Wichtige Information',
                'verbose_name_plural': 'Wichtige Informationen',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TransferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='transfers/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='transfers.transfer')),
            ],
            options={
                'verbose_name': 'Transfer-Bild',
                'verbose_name_plural': 'Transfer-Bilder',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='transfers.transfertype'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='vehicle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='transfers.vehicletype'),
        ),
        migrations.CreateModel(
            name='TransferRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Entfernung (km)')),
                ('estimated_duration', models.PositiveIntegerField(verbose_name='Geschätzte Dauer (Minuten)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis (EUR)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_routes_from', to='tours.location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_routes_to', to='tours.location')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transfers.transfer')),
            ],
            options={
                'verbose_name': 'Transfer-Route',
                'verbose_name_plural': 'Transfer-Routen',
                'ordering': ['order', 'from_location', 'to_location'],
                'unique_together': {('transfer', 'from_location', 'to_location')},
            },
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['slug'], name='transfers_t_slug_d4accf_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['is_active', 'is_featured'], name='transfers_t_is_acti_9fdb68_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['transfer_type', 'is_active'], name='transfers_t_transfe_7fffaa_idx'),
        ),
    ]
