# Generated by Django 4.2.8 on 2026-01-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_alter_transfer_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Transfer Image', 'verbose_name_plural': 'Transfer Images'},
        ),
        migrations.AlterModelOptions(
            name='transferimportantinfo',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Important Information', 'verbose_name_plural': 'Important Information'},
        ),
        migrations.AlterModelOptions(
            name='transferinclusion',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Inclusion', 'verbose_name_plural': 'Inclusions'},
        ),
        migrations.AlterModelOptions(
            name='transferroute',
            options={'ordering': ['order', 'from_location', 'to_location'], 'verbose_name': 'Transfer Route', 'verbose_name_plural': 'Transfer Routes'},
        ),
        migrations.AlterModelOptions(
            name='transfertype',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Transfer Type', 'verbose_name_plural': 'Transfer Types'},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'ordering': ['order', 'capacity'], 'verbose_name': 'Vehicle Type', 'verbose_name_plural': 'Vehicle Types'},
        ),
    ]
