# Generated by Django 4.2.8 on 2026-01-07 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name (DE)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (EN)')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung (DE)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Standort',
                'verbose_name_plural': 'Standorte',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel (DE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(verbose_name='Beschreibung (DE)')),
                ('description_en', models.TextField(verbose_name='Description (EN)')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Kurzbeschreibung (DE)')),
                ('short_description_en', models.CharField(blank=True, max_length=300, verbose_name='Short Description (EN)')),
                ('featured_image', models.ImageField(upload_to='tours/', verbose_name='Hauptbild')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis (EUR)')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Originalpreis')),
                ('duration', models.CharField(max_length=100, verbose_name='Dauer')),
                ('group_type', models.CharField(choices=[('private', 'Privat'), ('small_group', 'Kleine Gruppe'), ('group', 'Gruppe')], default='group', max_length=50, verbose_name='Gruppentyp')),
                ('max_participants', models.PositiveIntegerField(default=20, verbose_name='Max. Teilnehmer')),
                ('min_age', models.PositiveIntegerField(default=0, verbose_name='Mindestalter')),
                ('languages', models.CharField(default='Deutsch, English', max_length=200, verbose_name='Sprachen')),
                ('available_days', models.CharField(default='Täglich', max_length=200, verbose_name='Verfügbare Tage')),
                ('pickup_included', models.BooleanField(default=True, verbose_name='Abholung inklusive')),
                ('pickup_time', models.CharField(blank=True, max_length=100, verbose_name='Abholzeit')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Hervorgehoben')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Touren',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name (DE)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (EN)')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung (DE)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('icon', models.CharField(blank=True, help_text='CSS class for icon', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tour-Kategorie',
                'verbose_name_plural': 'Tour-Kategorien',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TourInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='Element (DE)')),
                ('item_en', models.CharField(max_length=200, verbose_name='Item (EN)')),
                ('is_included', models.BooleanField(default=True, verbose_name='Inklusive')),
                ('order', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Inklusive/Exklusive',
                'verbose_name_plural': 'Inklusive/Exklusive',
                'ordering': ['is_included', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Bildunterschrift')),
                ('caption_en', models.CharField(blank=True, max_length=200, verbose_name='Caption (EN)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Tour-Bild',
                'verbose_name_plural': 'Tour-Bilder',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='tours.tourcategory'),
        ),
        migrations.AddField(
            model_name='tour',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.location'),
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, verbose_name='Zeit')),
                ('title', models.CharField(max_length=200, verbose_name='Titel (DE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('description', models.TextField(verbose_name='Beschreibung (DE)')),
                ('description_en', models.TextField(verbose_name='Description (EN)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Reiseverlauf',
                'verbose_name_plural': 'Reiseverläufe',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['slug'], name='tours_tour_slug_a32940_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['is_active', 'is_featured'], name='tours_tour_is_acti_1b8fef_idx'),
        ),
    ]
