# Generated by Django 4.2.8 on 2026-01-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_location_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['order'], 'verbose_name': 'Itinerary', 'verbose_name_plural': 'Itineraries'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tour', 'verbose_name_plural': 'Tours'},
        ),
        migrations.AlterModelOptions(
            name='tourcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Tour Category', 'verbose_name_plural': 'Tour Categories'},
        ),
        migrations.AlterModelOptions(
            name='tourimage',
            options={'ordering': ['order'], 'verbose_name': 'Tour Image', 'verbose_name_plural': 'Tour Images'},
        ),
        migrations.AlterModelOptions(
            name='tourinclusion',
            options={'ordering': ['is_included', 'order'], 'verbose_name': 'Inclusion/Exclusion', 'verbose_name_plural': 'Inclusions/Exclusions'},
        ),
    ]
