# Generated by Django 4.2.8 on 2026-01-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AusflugÄgypten', max_length=200, verbose_name='Seitenname')),
                ('site_title', models.CharField(default='AusflugÄgypten - Touren, Ausflüge & Aktivitäten in Ägypten', max_length=200, verbose_name='Seitentitel')),
                ('site_description', models.TextField(default='Entdecken Sie die besten Touren und Ausflüge in Ägypten', verbose_name='Seitenbeschreibung')),
                ('site_keywords', models.CharField(default='Ägypten Touren, Hurghada Ausflüge, Luxor, Kairo', max_length=500, verbose_name='Keywords')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('logo_alt', models.CharField(default='AusflugÄgypten Logo', max_length=200, verbose_name='Logo Alt Text')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon')),
                ('address', models.CharField(default='Hurghada, Ägypten', max_length=500, verbose_name='Adresse')),
                ('phone', models.CharField(default='+20 123 456 7890', max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(default='info@ausflugagypten.com', max_length=254, verbose_name='E-Mail')),
                ('whatsapp', models.CharField(default='+201234567890', max_length=50, verbose_name='WhatsApp')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('opening_hours_monday_friday', models.CharField(default='08:00 - 20:00', max_length=100, verbose_name='Montag - Freitag')),
                ('opening_hours_saturday', models.CharField(default='09:00 - 18:00', max_length=100, verbose_name='Samstag')),
                ('opening_hours_sunday', models.CharField(default='10:00 - 16:00', max_length=100, verbose_name='Sonntag')),
                ('footer_text', models.TextField(default='Erleben Sie unvergessliche Abenteuer in Ägypten mit unseren maßgeschneiderten Touren und Ausflügen.', verbose_name='Footer Text')),
                ('copyright_text', models.CharField(default='© 2024 AusflugÄgypten. Alle Rechte vorbehalten.', max_length=200, verbose_name='Copyright Text')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Open Graph Bild')),
            ],
            options={
                'verbose_name': 'Seiteneinstellungen',
                'verbose_name_plural': 'Seiteneinstellungen',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('subject', models.CharField(choices=[('tour_booking', 'Tourbuchung'), ('general_inquiry', 'Allgemeine Anfrage'), ('complaint', 'Beschwerden'), ('other', 'Sonstiges')], max_length=50, verbose_name='Betreff')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('status', models.CharField(choices=[('new', 'Neu'), ('read', 'Gelesen'), ('replied', 'Beantwortet'), ('archived', 'Archiviert')], default='new', max_length=20, verbose_name='Status')),
                ('is_read', models.BooleanField(default=False, verbose_name='Gelesen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notizen')),
            ],
            options={
                'verbose_name': 'Kontaktnachricht',
                'verbose_name_plural': 'Kontaktnachrichten',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='core_contac_status_a0adbc_idx'), models.Index(fields=['is_read', '-created_at'], name='core_contac_is_read_67cbaf_idx')],
            },
        ),
    ]
