# Generated by Django 4.2.8 on 2026-01-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Abonniert am')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgemeldet am')),
            ],
            options={
                'verbose_name': 'Newsletter Abonnent',
                'verbose_name_plural': 'Newsletter Abonnenten',
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['email', 'is_active'], name='core_newsle_email_f1540c_idx')],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Hintergrundbild')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('subtitle', models.TextField(verbose_name='Untertitel')),
                ('button_1_text', models.CharField(blank=True, max_length=100, verbose_name='Button 1 Text')),
                ('button_1_url', models.CharField(blank=True, help_text="URL oder Django URL Name (z.B. 'excursions:list')", max_length=500, verbose_name='Button 1 URL')),
                ('button_1_style', models.CharField(choices=[('primary', 'Primary Button'), ('outline', 'Outline Button')], default='primary', max_length=20, verbose_name='Button 1 Stil')),
                ('button_2_text', models.CharField(blank=True, max_length=100, verbose_name='Button 2 Text')),
                ('button_2_url', models.CharField(blank=True, help_text="URL oder Django URL Name (z.B. 'core:contact')", max_length=500, verbose_name='Button 2 URL')),
                ('button_2_style', models.CharField(choices=[('primary', 'Primary Button'), ('outline', 'Outline Button')], default='outline', max_length=20, verbose_name='Button 2 Stil')),
                ('order', models.PositiveIntegerField(default=0, help_text='Niedrigere Zahlen werden zuerst angezeigt', verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='core_herosl_is_acti_422ef5_idx')],
            },
        ),
    ]
