# Generated by Django 4.2.8 on 2026-01-08 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newslettersubscriber_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('excursions', 'Ausflüge & Touren'), ('blog', 'Blog'), ('gallery', 'Galerie'), ('transfers', 'Transfer Service'), ('activities', 'Aktivitäten')], max_length=50, unique=True, verbose_name='Seite')),
                ('background_image', models.ImageField(upload_to='hero/pages/', verbose_name='Hintergrundbild')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('subtitle', models.TextField(verbose_name='Untertitel/Beschreibung')),
                ('breadcrumb_text', models.CharField(blank=True, help_text='Falls leer, wird der Seitentitel verwendet', max_length=100, verbose_name='Breadcrumb Text')),
                ('height', models.CharField(default='450px', help_text="z.B. '450px' oder '500px'", max_length=20, verbose_name='Höhe')),
                ('overlay_opacity', models.CharField(default='0.7', help_text="z.B. '0.7' für 70% Deckkraft", max_length=20, verbose_name='Overlay Opacity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Seiten Hero',
                'verbose_name_plural': 'Seiten Heroes',
                'ordering': ['page'],
            },
        ),
        migrations.CreateModel(
            name='PageHeroBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, help_text='SVG Path oder Emoji', max_length=100, verbose_name='Icon')),
                ('text', models.CharField(max_length=100, verbose_name='Text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('page_hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='core.pagehero', verbose_name='Seiten Hero')),
            ],
            options={
                'verbose_name': 'Hero Badge',
                'verbose_name_plural': 'Hero Badges',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='pagehero',
            index=models.Index(fields=['page', 'is_active'], name='core_pagehe_page_df597f_idx'),
        ),
    ]
