# Generated by Django 4.2.8 on 2026-01-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pagehero_pageherobadge_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'ordering': ['-subscribed_at'], 'verbose_name': 'Newsletter Subscriber', 'verbose_name_plural': 'Newsletter Subscribers'},
        ),
        migrations.AlterModelOptions(
            name='pagehero',
            options={'ordering': ['page'], 'verbose_name': 'Page Hero', 'verbose_name_plural': 'Page Heroes'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
    ]
