# Generated by Django 4.2.8 on 2026-01-07 01:02

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name (DE)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (EN)')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog-Kategorie',
                'verbose_name_plural': 'Blog-Kategorien',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel (DE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Inhalt (DE)')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content (EN)')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='Auszug (DE)')),
                ('excerpt_en', models.CharField(blank=True, max_length=300, verbose_name='Excerpt (EN)')),
                ('featured_image', models.ImageField(upload_to='blog/', verbose_name='Hauptbild')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
                ('is_published', models.BooleanField(default=False, verbose_name='Veröffentlicht')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_time', models.PositiveIntegerField(default=5, verbose_name='Lesezeit (Minuten)')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog-Artikel',
                'verbose_name_plural': 'Blog-Artikel',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx'), models.Index(fields=['is_published', '-published_at'], name='blog_blogpo_is_publ_cd7c82_idx')],
            },
        ),
    ]
