# Generated by Django 4.2.8 on 2026-01-08 18:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Inhalt (DE)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_en',
            field=tinymce.models.HTMLField(verbose_name='Content (EN)'),
        ),
    ]
