# Generated by Django 4.2.8 on 2026-01-08 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Land')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('language_preference', models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], default='de', max_length=2, verbose_name='Bevorzugte Sprache')),
                ('newsletter_subscribed', models.BooleanField(default=False, verbose_name='Newsletter abonniert')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profilbild')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benutzerprofil',
                'verbose_name_plural': 'Benutzerprofile',
            },
        ),
    ]
