# Generated by Django 4.2.8 on 2026-01-07 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name (DE)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (EN)')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung (DE)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon (e.g., 🏖️, 🏛️, 🏜️)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Galerie-Kategorie',
                'verbose_name_plural': 'Galerie-Kategorien',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel (DE)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Title (EN)')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung (DE)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Bild')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/', verbose_name='Vorschaubild')),
                ('photographer', models.CharField(blank=True, max_length=200, verbose_name='Fotograf')),
                ('taken_at', models.DateField(blank=True, null=True, verbose_name='Aufgenommen am')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt-Text')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Hervorgehoben')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='gallery.gallerycategory')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='tours.location')),
            ],
            options={
                'verbose_name': 'Galerie-Bild',
                'verbose_name_plural': 'Galerie-Bilder',
                'ordering': ['order', '-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'is_featured'], name='gallery_gal_is_acti_46e81d_idx'), models.Index(fields=['category', 'is_active'], name='gallery_gal_categor_45015e_idx'), models.Index(fields=['location', 'is_active'], name='gallery_gal_locatio_455428_idx')],
            },
        ),
    ]
