# Generated by Django 4.2.8 on 2026-01-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Gallery Category', 'verbose_name_plural': 'Gallery Categories'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order', '-is_featured', '-created_at'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
    ]
