# Generated by Django 4.2.8 on 2026-01-07 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Name')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('customer_phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('booking_date', models.DateField(verbose_name='Buchungsdatum')),
                ('number_of_participants', models.PositiveIntegerField(default=1, verbose_name='Anzahl Teilnehmer')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gesamtpreis')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('confirmed', 'Bestätigt'), ('cancelled', 'Storniert'), ('completed', 'Abgeschlossen')], default='pending', max_length=20, verbose_name='Status')),
                ('special_requests', models.TextField(blank=True, verbose_name='Besondere Wünsche')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin-Notizen')),
                ('confirmation_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Buchung',
                'verbose_name_plural': 'Buchungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=200, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Betrag')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Währung')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('processing', 'In Bearbeitung'), ('succeeded', 'Erfolgreich'), ('failed', 'Fehlgeschlagen'), ('refunded', 'Erstattet')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Zahlung',
                'verbose_name_plural': 'Zahlungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['confirmation_code'], name='bookings_bo_confirm_783da7_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', '-created_at'], name='bookings_bo_status_eb4fb1_idx'),
        ),
    ]
