# Generated by Django 4.2.8 on 2026-01-08 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
        ('bookings', '0002_booking_activity_booking_excursion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='transfers.transfer'),
        ),
    ]
