# Generated by Django 4.2.8 on 2026-01-07 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel (DE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(verbose_name='Beschreibung (DE)')),
                ('description_en', models.TextField(verbose_name='Description (EN)')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Kurzbeschreibung (DE)')),
                ('short_description_en', models.CharField(blank=True, max_length=300, verbose_name='Short Description (EN)')),
                ('featured_image', models.ImageField(upload_to='excursions/', verbose_name='Hauptbild')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis (EUR)')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Originalpreis')),
                ('duration', models.CharField(max_length=100, verbose_name='Dauer')),
                ('group_type', models.CharField(choices=[('private', 'Privat'), ('small_group', 'Kleine Gruppe'), ('group', 'Gruppe')], default='group', max_length=50, verbose_name='Gruppentyp')),
                ('max_participants', models.PositiveIntegerField(default=20, verbose_name='Max. Teilnehmer')),
                ('min_age', models.PositiveIntegerField(default=0, verbose_name='Mindestalter')),
                ('languages', models.CharField(default='Deutsch, English', max_length=200, verbose_name='Sprachen')),
                ('available_days', models.CharField(default='Täglich', max_length=200, verbose_name='Verfügbare Tage')),
                ('pickup_included', models.BooleanField(default=True, verbose_name='Abholung inklusive')),
                ('pickup_time', models.CharField(blank=True, max_length=100, verbose_name='Abholzeit')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Hervorgehoben')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Beliebt')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Bestseller')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursions', to='tours.tourcategory')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursions', to='tours.location')),
            ],
            options={
                'verbose_name': 'Ausflug',
                'verbose_name_plural': 'Ausflüge',
                'ordering': ['-is_bestseller', '-is_popular', '-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExcursionItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, verbose_name='Zeit')),
                ('title', models.CharField(max_length=200, verbose_name='Titel (DE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('description', models.TextField(verbose_name='Beschreibung (DE)')),
                ('description_en', models.TextField(verbose_name='Description (EN)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='excursions.excursion')),
            ],
            options={
                'verbose_name': 'Reiseverlauf',
                'verbose_name_plural': 'Reiseverläufe',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExcursionInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='Element (DE)')),
                ('item_en', models.CharField(max_length=200, verbose_name='Item (EN)')),
                ('is_included', models.BooleanField(default=True, verbose_name='Inklusive')),
                ('order', models.PositiveIntegerField(default=0)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='excursions.excursion')),
            ],
            options={
                'verbose_name': 'Inklusive/Exklusive',
                'verbose_name_plural': 'Inklusive/Exklusive',
                'ordering': ['is_included', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExcursionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='excursions/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Bildunterschrift')),
                ('caption_en', models.CharField(blank=True, max_length=200, verbose_name='Caption (EN)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='excursions.excursion')),
            ],
            options={
                'verbose_name': 'Ausflug-Bild',
                'verbose_name_plural': 'Ausflug-Bilder',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='excursion',
            index=models.Index(fields=['slug'], name='excursions__slug_4ccc74_idx'),
        ),
        migrations.AddIndex(
            model_name='excursion',
            index=models.Index(fields=['is_active', 'is_featured', 'is_popular'], name='excursions__is_acti_4ed480_idx'),
        ),
        migrations.AddIndex(
            model_name='excursion',
            index=models.Index(fields=['location', 'is_active'], name='excursions__locatio_5aa091_idx'),
        ),
        migrations.AddIndex(
            model_name='excursion',
            index=models.Index(fields=['category', 'is_active'], name='excursions__categor_607f95_idx'),
        ),
    ]
