# Generated by Django 4.2.8 on 2026-01-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0002_alter_excursion_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursion',
            options={'ordering': ['-is_bestseller', '-is_popular', '-is_featured', '-created_at'], 'verbose_name': 'Excursion', 'verbose_name_plural': 'Excursions'},
        ),
        migrations.AlterModelOptions(
            name='excursionimage',
            options={'ordering': ['order'], 'verbose_name': 'Excursion Image', 'verbose_name_plural': 'Excursion Images'},
        ),
        migrations.AlterModelOptions(
            name='excursioninclusion',
            options={'ordering': ['is_included', 'order'], 'verbose_name': 'Inclusion/Exclusion', 'verbose_name_plural': 'Inclusions/Exclusions'},
        ),
        migrations.AlterModelOptions(
            name='excursionitinerary',
            options={'ordering': ['order'], 'verbose_name': 'Itinerary', 'verbose_name_plural': 'Itineraries'},
        ),
    ]
