# Generated by Django 4.2.8 on 2026-01-07 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel (DE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Kurzbeschreibung (DE)')),
                ('short_description_en', models.CharField(blank=True, max_length=300, verbose_name='Short Description (EN)')),
                ('description', models.TextField(verbose_name='Beschreibung (DE)')),
                ('description_en', models.TextField(verbose_name='Description (EN)')),
                ('featured_image', models.ImageField(upload_to='activities/', verbose_name='Hauptbild')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis (EUR)')),
                ('price_per_person', models.BooleanField(default=True, verbose_name='Preis pro Person')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rabattpreis')),
                ('duration_hours', models.PositiveIntegerField(default=4, verbose_name='Dauer (Stunden)')),
                ('group_size', models.CharField(choices=[('Privat', 'Privat'), ('Klein', 'Klein (2-8 Personen)'), ('Mittel', 'Mittel (9-15 Personen)'), ('Groß', 'Groß (16+ Personen)')], default='Klein', max_length=50, verbose_name='Gruppengröße')),
                ('languages', models.CharField(default='DE, EN', help_text="Komma-getrennte Liste (z.B. 'DE, EN, FR')", max_length=200, verbose_name='Verfügbare Sprachen')),
                ('pickup_included', models.BooleanField(default=True, verbose_name='Abholung inklusive')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Empfohlen')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Beliebt')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aktivität',
                'verbose_name_plural': 'Aktivitäten',
                'ordering': ['-is_featured', '-is_popular', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name (DE)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (EN)')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung (DE)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon class (e.g., 🏊, 🏛️, 🏜️)', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_categories/')),
                ('gradient_color', models.CharField(default='primary-blue', help_text='CSS gradient color class (primary-blue, primary-gold, orange-600)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Aktivitäts-Kategorie',
                'verbose_name_plural': 'Aktivitäts-Kategorien',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel (DE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='activities.activity')),
            ],
            options={
                'verbose_name': 'Inklusion',
                'verbose_name_plural': 'Inklusionen',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityImportantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=300, verbose_name='Information (DE)')),
                ('info_en', models.CharField(max_length=300, verbose_name='Information (EN)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_info', to='activities.activity')),
            ],
            options={
                'verbose_name': 'Wichtige Information',
                'verbose_name_plural': 'Wichtige Informationen',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activities.activity')),
            ],
            options={
                'verbose_name': 'Aktivitäts-Bild',
                'verbose_name_plural': 'Aktivitäts-Bilder',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='activities.activitycategory'),
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='tours.location'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['slug'], name='activities__slug_6b6c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['is_active', 'is_featured'], name='activities__is_acti_1ecf9b_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['category', 'is_active'], name='activities__categor_731fa5_idx'),
        ),
    ]
