# Generated by Django 4.2.8 on 2026-01-08 18:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Beschreibung (DE)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description_en',
            field=tinymce.models.HTMLField(verbose_name='Description (EN)'),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Beschreibung (DE)'),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Description (EN)'),
        ),
    ]
