# Generated by Django 4.2.8 on 2026-01-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-is_featured', '-is_popular', 'title'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='activitycategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Activity Category', 'verbose_name_plural': 'Activity Categories'},
        ),
        migrations.AlterModelOptions(
            name='activityimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Activity Image', 'verbose_name_plural': 'Activity Images'},
        ),
        migrations.AlterModelOptions(
            name='activityimportantinfo',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Important Information', 'verbose_name_plural': 'Important Information'},
        ),
        migrations.AlterModelOptions(
            name='activityinclusion',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Inclusion', 'verbose_name_plural': 'Inclusions'},
        ),
    ]
